export const GET_WEB_PROJECTS = 'GET_WEB_PROJECTS'
export const WEB_PROJECTS_LOADING = 'WEB_PROJECTS_LOADING'
export const GET_INTER_PROJECTS = 'GET_INTER_PROJECTS'
export const INTER_PROJECTS_LOADING = 'INTER_PROJECTS_LOADING'